In [100]:
import sys
import importlib
from pathlib import Path

import chainladder as cl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

repo_root = Path.cwd().parent.parent
sys.path.insert(0, str(repo_root))
import src.reserving_utils as reserving_utils
importlib.reload(reserving_utils)
ReservingProjection = reserving_utils.ReservingProjection
load_triangle = reserving_utils.load_triangle
lag_triangle = reserving_utils.lag_triangle

clrd_path = repo_root / "data/raw/reserving/clrd2025.csv"
raa_path = repo_root / "data/raw/reserving/raa.csv"

projection_method = cl.Chainladder
development_params = {
    "average": "volume",
    "n_periods": -1,
}
method_params = {}

tri = load_triangle(
    clrd_path,
    origin_column="AccidentYear",
    development_column="DevelopmentYear",
    value_column="IncurredLosses",
    lob="wkcomp",
    company="Allstate Ins Co Grp",
    valuation_year=2007,
 )
tri_lagged = lag_triangle(tri)

reserving = ReservingProjection(
    tri,
    development_params=development_params,
    method=projection_method,
    method_params=method_params,
 )
reserving_lagged = ReservingProjection(
    tri_lagged,
    development_params=development_params,
    method=projection_method,
    method_params=method_params,
 )

raa_tri = load_triangle(raa_path)
raa_tri_lagged = lag_triangle(raa_tri)
raa_reserving = ReservingProjection(
    raa_tri,
    development_params=development_params,
    method=projection_method,
    method_params=method_params,
 )
raa_reserving_lagged = ReservingProjection(
    raa_tri_lagged,
    development_params=development_params,
    method=projection_method,
    method_params=method_params,
 )

c:\Users\gawlo\Documents\github\py_projects\TabPFN\.venv\Lib\site-packages\chainladder\utils\weighted_regression.py:84: RuntimeWarning: invalid value encountered in sqrt
  residual = (y - fitted_value) * xp.sqrt(w)
c:\Users\gawlo\Documents\github\py_projects\TabPFN\.venv\Lib\site-packages\chainladder\development\development.py:174: RuntimeWarning: invalid value encountered in sqrt
  / xp.swapaxes(xp.sqrt(x ** (2 - exponent))[..., 0:1, :], -1, -2)
c:\Users\gawlo\Documents\github\py_projects\TabPFN\.venv\Lib\site-packages\chainladder\development\development.py:185: RuntimeWarning: invalid value encountered in sqrt
  std = xp.sqrt((1 / num_to_nan(w)) * (self.sigma_**2).values)
c:\Users\gawlo\Documents\github\py_projects\TabPFN\.venv\Lib\site-packages\chainladder\utils\weighted_regression.py:84: RuntimeWarning: invalid value encountered in sqrt
  residual = (y - fitted_value) * xp.sqrt(w)
c:\Users\gawlo\Documents\github\py_projects\TabPFN\.venv\Lib\site-packages\chainladder\development\development.py:174: RuntimeWarning: invalid value encountered in sqrt
  / xp.swapaxes(xp.sqrt(x ** (2 - exponent))[..., 0:1, :], -1, -2)
c:\Users\gawlo\Documents\github\py_projects\TabPFN\.venv\Lib\site-packages\chainladder\development\development.py:185: RuntimeWarning: invalid value encountered in sqrt
  std = xp.sqrt((1 / num_to_nan(w)) * (self.sigma_**2).values)

In [101]:
tri.head(50)

    origin  development  values
0     1998         1998   10079
1     1998         1999    9643
2     1998         2000    3207
3     1998         2001    3202
4     1998         2002    3197
5     1998         2003    3181
6     1998         2004    3181
7     1998         2005    3181
8     1998         2006    3201
9     1998         2007    3200
10    1999         1999   12261
11    1999         2000     836
12    1999         2001     834
13    1999         2002     825
14    1999         2003     825
15    1999         2004     825
16    1999         2005     825
17    1999         2006     825
18    1999         2007     825
19    2000         2000    -621
20    2000         2001    -629
21    2000         2002    -633
22    2000         2003    -633
23    2000         2004    -633
24    2000         2005    -633
25    2000         2006    -633
26    2000         2007    -633
27    2001         2001       0
28    2001         2002       3
29    2001         2003       1
30    2001         2004       1
31    2001         2005       4
32    2001         2006       1
33    2001         2007       2
34    2002         2002       3
35    2002         2003       1
36    2002         2004       1
37    2002         2005       1
38    2002         2006       1
39    2002         2007       1
40    2003         2003       0
41    2003         2004       0
42    2003         2005       1
43    2003         2006       3
44    2003         2007       3
45    2004         2004       0
46    2004         2005       0
47    2004         2006       0
48    2004         2007       0
49    2005         2005       0

In [93]:
reserving_lagged.triangle

          12      24      36      48      60      72      84      96      108
1998  10079.0  9643.0  3207.0  3202.0  3197.0  3181.0  3181.0  3181.0  3201.0
1999  12261.0   836.0   834.0   825.0   825.0   825.0   825.0   825.0     NaN
2000   -621.0  -629.0  -633.0  -633.0  -633.0  -633.0  -633.0     NaN     NaN
2001      NaN     3.0     1.0     1.0     4.0     1.0     NaN     NaN     NaN
2002      3.0     1.0     1.0     1.0     1.0     NaN     NaN     NaN     NaN
2003      NaN     NaN     1.0     3.0     NaN     NaN     NaN     NaN     NaN
2004      NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2005      NaN     3.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2006      NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN

In [94]:
reserving.claims_triangle

          12      24      36      48      60      72      84      96      108     120
1998  10079.0  9643.0  3207.0  3202.0  3197.0  3181.0  3181.0  3181.0  3201.0  3200.0
1999  12261.0   836.0   834.0   825.0   825.0   825.0   825.0   825.0   825.0     NaN
2000   -621.0  -629.0  -633.0  -633.0  -633.0  -633.0  -633.0  -633.0     NaN     NaN
2001      NaN     3.0     1.0     1.0     4.0     1.0     2.0     NaN     NaN     NaN
2002      3.0     1.0     1.0     1.0     1.0     1.0     NaN     NaN     NaN     NaN
2003      NaN     NaN     1.0     3.0     3.0     NaN     NaN     NaN     NaN     NaN
2004      NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2005      NaN     3.0     3.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2006      NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2007      NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN

In [95]:
reserving.ldf_triangle

          12-24     24-36     36-48     48-60     60-72     72-84  84-96    96-108   108-120  120-132  132-144
(All)  0.453503  0.346251  0.996482  0.999412  0.994402  1.000296    1.0  1.004993  0.999688      1.0      1.0

In [96]:
percent_developed = reserving.percent_developed(valuation_age=10)
percent_developed

,12,24,36,48,60,72,84,96,108,120
1998-01-01,3.149688,3.013438,1.002188,1.000625,0.999062,0.994062,0.994062,0.994062,1.000312,1.0
1999-01-01,14.866462,1.013650,1.011225,1.000312,1.000312,1.000312,1.000312,1.000312,1.000312,1.0
2000-01-01,0.976474,0.989054,0.995343,0.995343,0.995343,0.995343,0.995343,0.995343,1.000313,1.0
2001-01-01,NaN,1.493015,0.497672,0.497672,1.990686,0.497672,0.995343,0.995343,1.000312,1.0
2002-01-01,2.985145,0.995048,0.995048,0.995048,0.995048,0.995048,0.995343,0.995343,1.000312,1.0
2003-01-01,NaN,NaN,0.333550,1.000650,1.000650,0.995048,0.995343,0.995343,1.000313,1.0
2004-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-01-01,NaN,1.004774,1.004774,1.001239,1.000650,0.995048,0.995343,0.995343,1.000312,1.0
2006-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2007-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [97]:
reserving.ultimate_by_origin

               ultimate
1998-01-01  3200.000000
1999-01-01   824.742268
2000-01-01  -635.961522
2001-01-01     2.009357
2002-01-01     1.004976
2003-01-01     2.998051
2004-01-01          NaN
2005-01-01     2.985746
2006-01-01          NaN
2007-01-01          NaN

In [102]:
raa_reserving.ultimate_by_origin.join(
    raa_reserving_lagged.ultimate_by_origin,
    lsuffix="_full",
    rsuffix="_lagged",
 )

            ultimate_full  ultimate_lagged
1981-01-01   18834.000000     18662.000000
1982-01-01   16857.953917     16215.922077
1983-01-01   24083.370924     23799.848752
1984-01-01   28703.142163     28345.599447
1985-01-01   28926.736343     32508.046451
1986-01-01   19501.103184     18844.550993
1987-01-01   17749.302590     20613.273580
1988-01-01   24019.192510     20788.207625
1989-01-01   16044.984101     30126.377165
1990-01-01   18402.442529              NaN